name: modular

# repository:
# command:
#   version:
#     linkToCommits: true
#     workspaceChangelog: true

packages:
  - .
  - packages/**

scripts:
  # Setup env and git hooks via Hanzo
  postbootstrap: >
    melos exec -- puro flutter pub get &&
    puro pub global activate git_hooks &&
    puro dart pub global activate full_coverage &&
    puro dart pub global activate flutter_gen &&
    puro dart pub global activate test_cov_console &&
    melos run dev:generate:i18n &&
    melos run dev:generate:native_splash &&
    melos run build_runner

  postclean: >
    melos exec -- puro flutter clean

  analyze:
    run: melos exec -- puro flutter analyze .
    description: Run `dart analyze` in all packages.

  # Start mobile apps scripts
  run:app:
    run: melos exec -- puro flutter run lib/main.dart
    packageFilters:
      flutter: true
      scope:
        - tradly_app

  # Generation i18n file
  dev:generate:i18n:
    run: melos exec --scope="tradly_app" -- "puro flutter pub run intl_utils:generate"
    description: "Generation localizations"
    packageFilters:
      flutter: true
      scope:
        - tradly_app

  # Generation icon launcher DEV version
  generate:icon_launcher_dev:
    run: melos exec -- puro flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons_dev.yaml
    description: "Generation icon launcher DEV version"
    packageFilters:
      scope:
        - tradly_app

  # Generation icon launcher PROD version
  generate:icon_launcher:
    run: melos exec -- puro flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons_prod.yaml
    description: "Generation icon launcher PROD version"
    packageFilters:
      scope:
        - tradly_app

  # Generation native splash
  dev:generate:native_splash:
    run: melos exec -- puro flutter pub run flutter_native_splash:create
    description: "Generation asset to display splash screen"
    packageFilters:
      scope:
        - tradly_app

  build_runner:
    run: |
      melos exec -- "puro flutter pub run build_runner build --delete-conflicting-outputs"
    packageFilters:
      ignore:
        - debugger
        - fluttertoast
        - date_picker_plus
        - open_mail_app
        - search_field

  # Unit testing scripts
  test:selective_unit_test:
    run: |
      melos exec -- \
      "full_coverage; \
      puro flutter test --fail-fast --no-pub --coverage -r expanded || exit 1; \
      lcov --remove coverage/lcov.info \
        $(echo '
        lib/api/*
        lib/env/*
        lib/main.dart
        lib/app_provider.dart
        lib/firebase_options.dart
        lib/main_device_preview.dart
        lib/configs/app_config.dart
        lib/configs/app_router.dart
        lib/configs/constants.dart
        lib/configs/router_guard.dart
        lib/extensions/*
        lib/features/auth/models/*
        lib/features/auth/view/*
        lib/features/browse/browse_screen.dart
        lib/features/auth/repositories/*
        lib/features/browse/repositories/*
        lib/features/home/models/*
        lib/features/home/repositories/*
        lib/features/home/views/*
        lib/features/home/home_screen.dart
        lib/features/payment/payment_option_screen.dart
        lib/features/product_detail/product_detail_screen.dart
        lib/features/profile/profile_screen.dart
        lib/features/store/store_screen.dart
        lib/features/wish_list/wish_list_screen.dart
        lib/features/on_boarding/*
        lib/features/order_history/order_history_screen.dart
        lib/features/payment/models/*
        lib/features/payment/states/*
        lib/features/payment/views/*
        lib/features/product_detail/repositories/*
        lib/features/product_detail/views/*
        lib/features/store/models/*
        lib/features/store/repositories/*
        lib/features/store/views/*
        lib/resources/l10n_generated/*
        lib/resources/l10n_generated/intl/*
        lib/service/*
        lib/themes/*
        lib/utils/*
        lib/widgets/*
        lib/widgets/layouts/*
        ' | tr '\n' ' ') -o coverage/lcov.info; \
      genhtml coverage/lcov.info --output=coverage/html; \
      open coverage/html/index.html"
    description: Run Flutter unit tests and generate coverage reports.
    packageFilters:
      flutter: true
      dirExists: test
      scope:
        - tradly_app
  test:
    run: melos run test:selective_unit_test --no-select
    description: Run all Flutter tests in this project.

  # Run unit test and generate html coverage (MacOS support for now)
  coverage:
    run: brew install lcov && melos run test
    description: Run unit testing and generate html coverage report.
    packageFilters:
      scope:
        - tradly_app
