name: tradly_app
description: "Tradly Application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Application dependencies
dependencies:
  flutter:
    sdk: flutter

  # Http client library for making API calls
  dio: ^5.5.0+1

  # Used for generating union types and data classes
  freezed: ^2.5.2

  # Helps implement value-based equality
  equatable: ^2.0.7

  # State management library based on BLoC pattern
  flutter_bloc: ^9.1.0

  # Renders SVG images in Flutter
  flutter_svg: ^2.0.17

  # Supabase client for Flutter
  supabase_flutter: ^2.8.4

  # Routing and navigation library
  go_router: ^15.1.2

  # Handles permissions for iOS and Android
  permission_handler: ^12.0.0+1

  # Provides internationalization and formatting utilities
  intl: ^0.20.2

  # Framework for responsive design
  responsive_framework: ^1.5.1

  # Adds native splash screens for iOS and Android
  flutter_native_splash: ^2.4.4

  # Generates localization code from ARB files
  intl_utils: ^2.8.5

  # Displays cached images from the internet
  cached_network_image: ^3.4.1

  # Environment variable management
  envied: ^1.1.1

  # Persistent storage for simple data
  shared_preferences: ^2.5.3

  # Firebase core library
  firebase_core: ^3.13.0

  # Firebase push notifications
  firebase_messaging: ^15.2.5

  # Local notifications for Flutter
  flutter_local_notifications: ^19.1.0

  # Freezed annotations for code generation
  freezed_annotation: ^2.4.4

  # Image picker for selecting images from the device
  image_picker: ^1.1.2

  # Preview application on different devices
  device_preview: ^1.2.0

  # Geolocation services
  geolocator: ^9.0.2

  # Geocoding services
  geocoding: ^2.0.5

  # Functional programming utilities
  fpdart: ^1.1.1

  # Overlay loader for async operations
  loader_overlay: ^5.0.0

  flutter_typeahead: ^5.2.0

  flutter_form_builder: ^10.0.1

  get_it: ^8.0.3    

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules for Flutter projects
  flutter_lints: ^5.0.0

  # Code generation tool
  build_runner: ^2.4.11

  # Generates launcher icons
  flutter_launcher_icons: ^0.14.3

  # Generates Flutter asset references
  flutter_gen_runner: ^5.10.0

  # Monorepo management tool
  melos: ^6.1.0

  # Code generator for envied
  envied_generator: ^1.1.1

  # Unit testing for BLoC
  bloc_test: ^10.0.0

  # Mocking library for tests
  mocktail: ^1.0.4

  # Fake data generator for tests
  faker: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

# Flutter Intl plugin configuration
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/resources/l10n_generated

# Flutter Gen plugin configuration
flutter_gen:
  output: lib/resources/assets_generated/
  integrations:
    flutter_svg: true
